services:
  # DATABASE
  db:
    image: mysql:8.0
    container_name: db_universita
    environment:
      MYSQL_DATABASE: universita_db # Ho dato un nome al DB
      MYSQL_ROOT_PASSWORD: root # Password semplice per lo sviluppo
    volumes:
      # Questa riga dice: "Prendi il file init.sql dalla cartella init_db
      # ed eseguilo appena il database si accende"
      - ./init_db:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"

  # APP (Il codice che userà i dati)
  app:
    build: .
    container_name: app_universita
    ports:
      - "5000:5000" # Porta standard, la cambiamo se serve
    depends_on:
      - db

    #connette i giusti percorsi ora per il codice python e il database nel container
    #permette di caricare nell'ambiente del container senza dover creare l'ambiente locamente
    volumes:
      - ./src:/app/src     # Mappa il codice (così se lo modifichi, si aggiorna)
      - ./data:/app/data   # Mappa la cartella dei dati (CSV sporchi e puliti)
      
    environment:
      # Queste sono le info che userai nel tuo codice per collegarti
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: universita_db
  # CLEANING (Servizio opzionale per pulire i dati)
  # Togli i "##" per abilitare questo servizio
  ##cleaning:
  ##  build: .
  ##  container_name: cleaning_universita
  ##  volumes:
  ##    - ./src:/app/src
  ##    - ./data:/app/data
  ##  command: ["/bin/bash", "/app/src/cleaning/clean_all.sh"]
  ##  depends_on:
  ##    - db

volumes:
  db_data:
