version: '3.8'

services:
  # DATABASE
  db:
    image: mysql:8.0
    container_name: db_universita
    environment:
      MYSQL_DATABASE: universita_db # Ho dato un nome al DB
      MYSQL_ROOT_PASSWORD: root # Password semplice per lo sviluppo
    volumes:
      # Questa riga dice: "Prendi il file init.sql dalla cartella init_db
      # ed eseguilo appena il database si accende"
      - ./init_db:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"

  # APP (Il codice che userà i dati)
  app:
    build: .
    container_name: app_universita
    ports:
      - "5000:5000" # Porta standard, la cambiamo se serve
    depends_on:
      - db
      ###rivisita questa sezione 27->43 tra le righe 48->58 di questo stesso file

      #questi volumes sono una aggiunta per gestire i file in data (prende csv psorchi da raw, passa agli script py e carica su processed i csv puliti)
      #togli i "##" per fargli fare così. per ora non ha senso perchè lavoro direttamente sui csv. se si volesse verificare che i csv usati combacino...
      #...effettivamente con quelli usati, abilitare le righe con "##" ricalcorerebbe i csv nel folder "processed"
      ##volumes:
      ##- ./src:/app/src     # Mappa il codice (così se lo modifichi, si aggiorna)
      #- ./src:/app/src: (Opzionale)
      #collega la cartella src locale a quella del container
      #vantaggio: Se modifico main.py o aggiungo uno script, non devo ricostruire l'immagine (docker-compose build) ogni volta. 
      #basta riavviare (docker-compose restart app)
      ##- ./data:/app/data   # Mappa la cartella dei dati (CSV sporchi e puliti)
      #- ./data:/app/data è quella fondamentale
      #docker prenderà la cartella dati che creo sul computer (nella cartella principale hackathon)
      #la renderà disponibile dentro il container al percorso /app/data
      #in questo modo, quando metti un CSV in hackathon/data/raw, Python lo vedrà in /app/data/raw
      #quando Python salverà il file pulito in /app/data/processed, apparirà pure sul computer
    environment:
      # Queste sono le info che userai nel tuo codice per collegarti
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: universita_db
  # CLEANING (Servizio opzionale per pulire i dati)
  # Togli i "##" per abilitare questo servizio
  ##cleaning:
  ##  build: .
  ##  container_name: cleaning_universita
  ##  volumes:
  ##    - ./src:/app/src
  ##    - ./data:/app/data
  ##  command: ["/bin/bash", "/app/src/cleaning/clean_all.sh"]
  ##  depends_on:
  ##    - db

volumes:
  db_data:
